services:
  flask:
    build:
      context: ./flask-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network

  streamlit:
    build:
      context: ./streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - flask
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
